# =========== 生产 ===========
prod_build:
  stage: build
  script:
    - echo "Building the app"
    - pwd
    - npm config set registry https://registry.npmmirror.com
    - npm i
    - npm run build:prod
    - rm -rf /server/eladmin/page/*
    - cp -r dist/* /server/eladmin/page/
  only:
    - main
  # tags:
  #   - xxxx
